package model.imagetransformation;

/**
 * Enum representing various image transformation methods.
 */
public enum Methods {
  GREYSCALE, SEPIA, BLUR, SHARPEN, VALUE_COMPONENT, INTENSITY_COMPONENT, LUMA_COMPONENT,
  RED_COMPONENT, GREEN_COMPONENT, BLUE_COMPONENT, BRIGHTEN, HORIZONTAL_FLIP, VERTICAL_FLIP,
  RGB_COMBINE, HISTOGRAM, COLOR_CORRECT, LEVELS_ADJUST, IMAGE_COMPRESSION, DITHER
}
